                ORG 40000
MUSICDATA:
                          DEFB 0   ; Loop start point * 2
                          DEFB 6   ; Song Length * 2
PATTERNDATA:              DEFW PAT0
                          DEFW PAT1
                          DEFW PAT2

; *** Pattern data consists of pairs of note values CH1,CH2 with a single $0 to
; *** mark the end of the pattern, and $01 for a rest
PAT0:
                          DEFB 2  ; Pattern tempo
                          DEFB 95,1
                          DEFB 1,93
                          DEFB 92,1
                          DEFB 1,93
                          DEFB 96,81
                          DEFB 1,1
                          DEFB 84,88
                          DEFB 1,1
                          DEFB 98,84
                          DEFB 1,96
                          DEFB 95,84
                          DEFB 1,96
                          DEFB 100,81
                          DEFB 1,1
                          DEFB 84,88
                          DEFB 1,1
                          DEFB 101,96
                          DEFB 1,88
                          DEFB 99,84
                          DEFB 1,1
                          DEFB 95,83
                          DEFB 1,105
                          DEFB 104,84
                          DEFB 1,105
                          DEFB 95,81
                          DEFB 1,105
                          DEFB 104,84
                          DEFB 1,105
                          DEFB 108,93
                          DEFB 1,1
                          DEFB 1,84
                          DEFB 1,1
                          DEFB 105,84
                          DEFB 1,1
                          DEFB 108,84
                          DEFB 103,1
                          DEFB 76,107
                          DEFB 1,1
                          DEFB 102,105
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 102,105
                          DEFB 103,1
                          DEFB 76,107
                          DEFB 1,1
                          DEFB 102,105
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 102,105
                          DEFB 103,1
                          DEFB 76,107
                          DEFB 1,1
                          DEFB 102,105
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 99,102
                          DEFB 1,1
                          DEFB 100,76
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
PAT1:
                          DEFB 2  ; Pattern tempo
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 98,101
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 105,100
                          DEFB 1,1
                          DEFB 101,88
                          DEFB 1,100
                          DEFB 98,95
                          DEFB 1,1
                          DEFB 1,91
                          DEFB 1,1
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 98,101
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 100,103
                          DEFB 1,1
                          DEFB 105,76
                          DEFB 1,103
                          DEFB 101,88
                          DEFB 1,100
                          DEFB 95,98
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 93,96
                          DEFB 1,1
                          DEFB 95,98
                          DEFB 1,1
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 101,72
                          DEFB 100,1
                          DEFB 98,84
                          DEFB 96,1
                          DEFB 95,92
                          DEFB 1,1
                          DEFB 1,88
                          DEFB 1,1
                          DEFB 93,96
                          DEFB 1,1
                          DEFB 95,98
                          DEFB 1,1
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 96,100
                          DEFB 1,1
                          DEFB 101,72
                          DEFB 100,1
                          DEFB 98,84
                          DEFB 96,1
                          DEFB 92,95
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
PAT2:
                          DEFB 2  ; Pattern tempo
                          DEFB 95,1
                          DEFB 1,93
                          DEFB 92,1
                          DEFB 1,93
                          DEFB 96,81
                          DEFB 1,1
                          DEFB 84,88
                          DEFB 1,1
                          DEFB 98,84
                          DEFB 1,96
                          DEFB 95,84
                          DEFB 1,96
                          DEFB 100,81
                          DEFB 1,1
                          DEFB 84,88
                          DEFB 1,1
                          DEFB 101,96
                          DEFB 1,88
                          DEFB 99,84
                          DEFB 1,1
                          DEFB 95,83
                          DEFB 1,105
                          DEFB 104,84
                          DEFB 1,105
                          DEFB 95,81
                          DEFB 1,105
                          DEFB 104,84
                          DEFB 1,105
                          DEFB 108,93
                          DEFB 1,1
                          DEFB 1,84
                          DEFB 1,1
                          DEFB 105,81
                          DEFB 1,1
                          DEFB 107,81
                          DEFB 1,1
                          DEFB 108,76
                          DEFB 1,1
                          DEFB 107,81
                          DEFB 1,1
                          DEFB 105,74
                          DEFB 1,1
                          DEFB 104,101
                          DEFB 1,1
                          DEFB 105,72
                          DEFB 1,1
                          DEFB 100,76
                          DEFB 1,1
                          DEFB 101,74
                          DEFB 1,1
                          DEFB 98,77
                          DEFB 1,1
                          DEFB 96,76
                          DEFB 1,1
                          DEFB 81,76
                          DEFB 1,1
                          DEFB 96,76
                          DEFB 96,1
                          DEFB 100,104
                          DEFB 1,93
                          DEFB 95,1
                          DEFB 93,69
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
